### ISSUE TITLE
REST API needs to be defined

### ISSUE THREAD

**Issue by kwalcock** [clulab/ConceptAlignment#10]
Here's a place for the discussion of the issue.

**Comment by kwalcock** [comment]
One of the [sample programs](https://github.com/clulab/ConceptAlignment/blob/master/src/main/scala/org/clulab/alignment/ExampleApp.scala) show my latest thinking about the functionality.

1. The API user submits a lucene query which is used on the variableDescription to find a (bottom-up) variable ID and associated information.
1. Include a maximum number of hits (even if lucene already has some other way to do this).  The program will also have an internal maximum.
1. Sort the hits by score.
1. For each hit find the vector and run knn to find the nearest top-down ontology hits.
1. Limit the number of those hits and sort by distance.
1. Return a json structure of maxLucene hits with maxKnn hits for each of those, all with appropriate accompanying information.

```scala
def rest(query: String, maxLucene: Int = 10, maxKnn: Int = 10): JSON
```

**Comment by MihaiSurdeanu** [comment]
I am not sure this captures the common usage. The common usage for this API will take as input as top-down (TD) concept, and will produce K bottom-up (BU) variables from the index. The key issue here is that there may be zero lexical overlap between the TD concept and the BU variables that match it. So, starting with a Lucene search (step 1) is probably not good, because it will not fetch the right BU variables.

What we had in mind, was to find the K nearest neighbors in embedding space from the BU variable index _directly_, without going through a Lucene index. This means that we need a fast kNN implementation for embeddings.

**Comment by kwalcock** [comment]
It sounds like I need to turn them around then.  I haven't yet lucene-indexed the top-down ontology, yet, but can on short order.  Is the rest REST reasonable?

**Comment by MihaiSurdeanu** [comment]
Yes, the rest of the REST seems Ok to me.

**Comment by kwalcock** [comment]
I should probably then describe the json that will be returned and make sure that method definition is complete and see if everyone including Brandon is OK with it.

**Comment by BeckySharp** [comment]
I think the lucene index is for filtering essentially, e.g., to lookup country etc.
so i think that the API is reasonable for sure, though for that usage the lucene topK should be much higher than the knn one
in terms of the backend, i agree that the most common use case (that we should implement first) is to:
- get the topk from both indexes
     - knn based on w2v similarity between query and concept embeddings of the BU things)
     - lucene based on a boolean query coming from the metadata and word overlap with description if its there (optional, but boost the score)
- intersect the results
- rank by the similarity score (or something)
- return ranked results

**Comment by kwalcock** [comment]
There are too many parts in that description that I don't understand, starting with the first line.  There are lucene indexes with top scores and knn indexes with best cosines and data in bottom-up variables, top-down ontology nodes, and glove vectors which can be mixed and matched, and various ways to map between texts and vectors, etc.

**Comment by kwalcock** [comment]
It seems like @BeckySharp is using Lucene to filter both at the top, giving n results, and bottom, giving m results, and then doing an n * m comparison to find best matches.  Is that so?  It doesn't seem like this works well with the annoy indexing, which is performed on the entire collection (usually offline, in advance).  Can it work well to index a subset on the fly unless n or m is extra large?  Maybe what is meant is there are (potentially) two lucene queries, one for top and one for bottom (and by default they could be the same in case there is lexical overlap).  It seems like one query would be enough, though, and that nearest neighbors could take care of the other end.

**Comment by MihaiSurdeanu** [comment]
@BeckySharp: do we need this Lucene filtering anymore?

**Comment by BeckySharp** [comment]
> It seems like @BeckySharp is using Lucene to filter both at the top, giving n results, and bottom, giving m results, and then doing an n * m comparison to find best matches. Is that so?

no -- instead I'm thinking that we'd get n results from annoy, and m results from a lucene metadata-based query, each result from each method has a unique "identifier", then we intersect the identifiers, and return the ones that survived, ranked.

> ... the annoy indexing, which is performed on the entire collection (usually offline, in advance). 
the "in advance" is only like a cache of the identity of the bottom-up thing (variable/indicator/etc), the comparison is always online

> Can it work well to index a subset on the fly unless n or m is extra large? 

I don't see why not

> Maybe what is meant is there are (potentially) two lucene queries, one for top and one for bottom (and by default they could be the same in case there is lexical overlap). It seems like one query would be enough, though, and that nearest neighbors could take care of the other end.

Not sure I follow, but maybe it's because of the misunderstanding surrounding the lucene index

@MihaiSurdeanu -- yes, I think we need the lucene filtering, so we can restrict results by location, time, etc.

**Comment by MihaiSurdeanu** [comment]
Ok, thanks!

I agree with Lucene to filter by loc/time. I was just worried that we plan to filter by *content*.

**Comment by kwalcock** [comment]
The "we'd get n results from annoy" throws me off right away.  What information is used to find these results in annoy?  You'll unconfuse me eventually, if you have enough patience.

**Comment by BeckySharp** [comment]
> The "we'd get n results from annoy" throws me off right away. What information is used to find these results in annoy? You'll unconfuse me eventually, if you have enough patience.

what i mean is that we will offline build an annoy-like index of the things we scraped from supermaas/datamarts.  Each of these things will have a vector representation of their meaning (and prob some metadata too, i imagine, but i've never used annoy).
At query time, we will receive a query with some type of text info as a String (examples, a description, whatever).  We will convert that to a vector representation using the same (or similar) approach we used to get the embeddings for the indexed things.  Then, we will use annoy to find the n most similar things in the index, using some vector-similarity metric.
these are what i'm referring to.  does that help?  it could be that I'm fundamentally misunderstanding something too

**Comment by BeckySharp** [comment]
> Ok, thanks!
> 
> I agree with Lucene to filter by loc/time. I was just worried that we plan to filter by _content_.

@MihaiSurdeanu -- while we shouldn't filter by content, if there **is** explicit word overlap, maybe we can boost the score somehow.  but that is def not required

**Comment by kwalcock** [comment]
Slowly, but surely...  This search of the bottom-up variables is "by example" rather than in some lucene query language.  The "query" is converted into a vector and then annoy can be used to find the nearest neighbors of the bottom-up variables.  I'm getting the feeling that the top-down part is non-existent.  Wasn't that supposed to be involved?

**Comment by BeckySharp** [comment]
now it's my turn :)
Which "top-down" part?  If you mean in the overall WM program sense of bottom-up (BU) and top-down (TD), then the TD part is the query coming in, aligned to the BU things that are indexed.  If you mean something else then i'll need clarification :)

ps -- +1 for you, @kwalcock

**Comment by kwalcock** [comment]
Apparently I imagined it.  By top-down I meant our existing Eidos ontologies like wm_flattened and their descriptions and vectors.  These would be something that some user would see because they are in the jsonld and then ask themselves whether there is any data collected for something like this.  That make sense with the Eidos dependencies, need for ontology managers, desire to read yaml format, etc.  (Remember that all the abbreviations and half the other words mean something else to me, or in the case of conceptBOWFromString, nothing else).

**Comment by BeckySharp** [comment]
you make a GREAT point here, and one I hadn't thought all the way to the end on.  The TD ontology concepts **are** involved, but they come in from the query.  that means that maybe we don't need any ontology loader etc at all, except perhaps in the evaluator subproject.  if so, that would be great!  I guess we may want to "look up" the concept embedding of the concept coming in, but that can be just a lookup-table, and require no fancy index or yaml, just a good old fashioned HashMap...

and conceptBOWFromString means take the string, split on whitespace, throw all the tokens in a bag, shake it up, and hope for an AI miracle in the form of a useful vector come Christmas

**Comment by kwalcock** [comment]
Regarding the indexing, we may have the choice between 1) having lucene search through 100,000 pre-indexed items, all the possibilities, and then doing the intersection as suggested, or maybe 2) indexing 100 items on the fly because they were the only ones matching the query by example and then checking the few against lucene, or 3) skipping the indexing of 100 items and just searching through them, the few, without the index.  In the latter two, lucene just filters the results of the first by example query.

**Comment by BeckySharp** [comment]
i like the idea of searching through all 100,000 preindexed items bc
otherwise we may not get a match in the top n of the other query.  With
lucene, that should be almost instant, right?

**Comment by kwalcock** [comment]
BOW = bag of words.  Hallelujah!  I had "beginning of word" once, but I thought O was for ontology and B was for bottom and whatever...

**Comment by kwalcock** [comment]
Does the "intersection of results" mean that the variable coming from the datamart has to in the top n nearest neighbors of the query by example _and_ the top m query by lucene matches?  If so, it seems like the order doesn't matter.  Calculating the intersection may be slow even if lucene is fast.  However, that's performance and I just need to get the right answer for now.

**Comment by kwalcock** [comment]
I hope this "query by example" term isn't a problem.  It used to be a thing--about the same time I had a Prodigy account ;-)

Just now it is sounding like
```scala
def rest(queryByExample: String, maxKnn: Int, queryByLucene:String, maxLucene: Int): JSON
```
I don't like my own description of the maxHits or whatever it is.  Max really means as close to but not over, because otherwise a single hit would satisfy maxHits = 100.  Doing the intersection and hoping that the intersection will have at least maxHits doesn't seem possible without collecting absolutely all hits, scoring them in both ways, combining the scores somehow, and sorting.  I'm thinking that it can be left to the user to decide how to divide the max up between the two kinds of searches.

**Comment by BeckySharp** [comment]
can we get say 100 hits from knn as an iterator, then iterate through them,
keeping ones that are in the results from lucene, until we get about n?
(for example) also, are there ways to ask annoy for the next k?

**Comment by kwalcock** [comment]
The JSON that is returned, just because this is REST, sounds like in pseudocode

case class JSONItem(datamartId, datasetId, variableId, veriableDescription, knnValue, luceneValue, combinedValue?)
type JSON = Array[JSONItem]

**Comment by kwalcock** [comment]
At least until the scores or distances or whatever are 0 or infinity, isn't it difficult to tell when one has collected the best combined score because the very worst of the one scores might combine with the very best of the other scores to produce a winner (it seems to me)... unless scores are sorted and one has already collected a number of them (maxHits) and one notices, knowing how scores are combined, than no combination of lower scores in either of the two categories can combine to form a score that would make the list.  It sounds fun if the interface supports it and if something is done to prevent the worst case of going through the entirety of both lists.  I was thinking more along the lines of take(n).

**Comment by BeckySharp** [comment]
if i understood that, then yes! :) at least as a starting point!

**Comment by BeckySharp** [comment]
that was a response to the json return

**Comment by kwalcock** [comment]
I still do not understand "The TD ontology concepts are involved, but they come in from the query".  Are they the query themselves?  We're not enforcing that someone is describing anything that is arranged into an ontology, like something that is structured and organized, are we?

I suspect that you would have completed the entire program by now :-(

**Comment by BeckySharp** [comment]
hahaha you’re hilarious :)
if you want to zoom we can, im awake or we can do tomorrow etc, e-mail me
if you’d like to

**Comment by kwalcock** [comment]
I will check the search interfaces to see if they have iterators and maybe check back tomorrow.  I need a break from myself anyway.

**Comment by kwalcock** [comment]
The annoy-type knn library does not provide an iterator.  The easiest thing to do is to ask for all the results and iterate through them.  Lucene doesn't seem to have an iterator, either, but it can be simulated by paging.  However, I think that the performance achieved by tracking down the absolute best hits based on the combined score will be very poor and I think very close to that of an exhaustive search through all scores, both those returned from the knn index and the lucene index.  The indexes are pretty useless in that case.

It is not clear to me how many results your union idea would return or how good the combined scores would be.  It probably depends on the query and the data.  It's easier to implement, though, and it seems worth the experiment.

**Comment by MihaiSurdeanu** [comment]
Wait. You can't get the top K results with the highest cosine similarity
with the query?

**Comment by kwalcock** [comment]
This issue, if I understand the question correctly, is that K must be specified in advance.  I was hoping to get an iterator to a list that was generated on the fly so that I could look through it until I could find K suitable elements.  Since they might not be found until the list is exhausted, K was going to have to be the size of the entire index.

> Wait. You can't get the top K results with the highest cosine similarity with the query?

**Comment by kwalcock** [comment]
Currently, these values below are scraped from the datamarts.  I had assumed that the location was going to be described in the dataset or variable description, possibly informally as text, which would make it a good candidate for Lucene.  It sounds like there might be an explicit or formal location field, which I will try to find.  If it is formal enough, then the location might be specified in some other way.  The user could pick through a list of possibilities, for example.

```scala
    tsvWriter.println("datamart_id",
      "dataset_id", "dataset_name", "dataset_description", "dataset_url",
      "variable_id", "variable_name", "variable_description"
```

**Comment by BeckySharp** [comment]
I think we should make fake locations, they can be randomly populated, just
to exercise the capability
I **don't** think we should try any harder to get the info from the current
datamarts, as, again, access will soon be through SuperMaaS with a
(hopefully) unified "API"

**Comment by kwalcock** [comment]
This is supposed to be a list of fields for each variable: https://datamart-upload.readthedocs.io/en/latest/download/ .  Country, for example, is there and I can use it for location as easily as generating fake ones.  What I am concerned about is the Lucene query and how it is specified because it goes into the REST interface.  Should it include search(country: Option[String], admin1: Option[String], admin2: Option[String]) or do they call def search(location: Option[String] = Some("country = 'ethiopia' && admin1 = 'woredas'")) or def search(words: Option[String] = Some("ethiopia woredas").  I'm hoping that Lucene has some kind of built-in syntax for searching across fields and that we can just allow for a string and pass it through to Lucene to figure it out.  So far I've always had to specify the Lucene field to search in code.  Do others already know how that works?

```scala
// Here the field and the query are specified separately.
new QueryParser(field, analyzer).parse(query)
```

**Comment by BeckySharp** [comment]
I don't want to bake the field names into the external API bc they will change when we go to supermaas.  
are you asking about a `search` method that we use internally to build the lucene queries? or the external one?
if the external, maybe we should the user pass in a filter Map[String, Seq[String])?

**Comment by kwalcock** [comment]
Right.  The map might necessitate a different call in which the names of fields can be queried.  The fields could also have "logical" names so that something like search(location: Option[String] = Some("somewhere")) is translated internally to country == "somewhere" || city == "somewhere" || admin1 == "somewhere".  If different fields are part of the query it would seem logical to return the values of the fields when they match.  So far I was only going to return the key and then maybe the description of the variable used to match the vectors.

The problem for the implementation is that there are too many ways to do it.  To be sure to have something rather than nothing, I'd be inclined to not yet include any Lucene search and stick with the vectors.  Maybe it would be simpleSearch() to see what happens.

**Comment by BeckySharp** [comment]
👍

**Comment by kwalcock** [comment]
This is currently hung up on a problem with the KNN library.  It works fine in the application, but not in the webap.  It seems to be a problem with serialization and class loaders.  It will not deserialize a class in the web context.  The next workaround is going to be to stuff the information into a string and see if that will work.  At least the string class should be available.

**Comment by BeckySharp** [comment]
thanks sir!

**Comment by kwalcock** [comment]
The v1 API is deployed, running, checked in, etc.
