### ISSUE TITLE
Cron job

### ISSUE THREAD

**Issue by BeckySharp** [clulab/ConceptAlignment#20]
Do we do this already?

**Comment by kwalcock** [comment]
The cron job is initiated by a human and an alarm clock.  I think it is too early to automatic this.  The SuperMaaS service is only available on a development machine, for instance.

**Comment by BeckySharp** [comment]
good call.

**Comment by kwalcock** [comment]
This is via API.  The URL of SuperMaaS is passed in as an environment variable when the webapp starts up.
